service: webhook-test

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  webhook:
    handler: dist/functions/webhookHandler.handler
    events:
      - http:
          path: webhook
          method: post
          cors: true
      - stream:
          arn: arn:aws:dynamodb:us-east-1:123456789012:table/MyTable/stream/2022-01-01T00:00:00.000
          batchSize: 5

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3006
    stage: dev
    region: us-east-1